### ISSUE TITLE
RemoteDisconnected issue when storing prediction results from two submissions at once

### ISSUE THREAD

**Issue by thomasyu888** [nlpsandbox/data-node#136]
```
STDERR: 2021-01-28T06:17:27.983046800Z 	    nlpsandbox/cli:edge \
STDERR: 2021-01-28T06:17:27.983050991Z 	    community \
STDERR: 2021-01-28T06:17:27.983055336Z 	    store-annotations \
STDERR: 2021-01-28T06:17:27.983059531Z 	    --annotation_json \
STDERR: 2021-01-28T06:17:27.983063776Z 	    /var/lib/cwl/stg7777c434-8ded-4e9b-bb58-991cc060f40b/predictions.json \
STDERR: 2021-01-28T06:17:27.983068171Z 	    --annotation_store_id \
STDERR: 2021-01-28T06:17:27.983072344Z 	    submission-9710064 \
STDERR: 2021-01-28T06:17:27.983076312Z 	    --data_node_host \
STDERR: 2021-01-28T06:17:27.983080555Z 	    http://10.23.54.142/api/v1/ \
STDERR: 2021-01-28T06:17:27.983084741Z 	    --dataset_id \
STDERR: 2021-01-28T06:17:27.983088899Z 	    2014-i2b2-20201203
STDERR: 2021-01-28T06:17:27.983093033Z 	Traceback (most recent call last):
STDERR: 2021-01-28T06:17:27.983097218Z 	  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
STDERR: 2021-01-28T06:17:27.983101764Z 	    httplib_response = self._make_request(
STDERR: 2021-01-28T06:17:27.983105977Z 	  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
STDERR: 2021-01-28T06:17:27.983110544Z 	    six.raise_from(e, None)
STDERR: 2021-01-28T06:17:27.983114727Z 	  File "<string>", line 3, in raise_from
STDERR: 2021-01-28T06:17:27.983119646Z 	  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
STDERR: 2021-01-28T06:17:27.983124259Z 	    httplib_response = conn.getresponse()
STDERR: 2021-01-28T06:17:27.983128494Z 	  File "/usr/local/lib/python3.8/http/client.py", line 1347, in getresponse
STDERR: 2021-01-28T06:17:27.983132915Z 	    response.begin()
STDERR: 2021-01-28T06:17:27.983137041Z 	  File "/usr/local/lib/python3.8/http/client.py", line 307, in begin
STDERR: 2021-01-28T06:17:27.983141351Z 	    version, status, reason = self._read_status()
STDERR: 2021-01-28T06:17:27.983149191Z 	  File "/usr/local/lib/python3.8/http/client.py", line 276, in _read_status
STDERR: 2021-01-28T06:17:27.983153638Z 	    raise RemoteDisconnected("Remote end closed connection without"
STDERR: 2021-01-28T06:17:27.983157954Z 	http.client.RemoteDisconnected: Remote end closed connection without response
```

**Comment by thomasyu888** [comment]
I run into this issue consistently whenever I submit the example person-annotator.  I then downloaded the prediction file and was actually able to upload it by doing:

```
nlp-cli community store-annotations --dataset_id awesome-dataset --annotation_store_id awesome-annotation-store --annotation_json predictions.json
```

**Comment by tschaffter** [comment]
This [ticket](https://stackoverflow.com/questions/48105448/python-http-server-client-remote-end-closed-connection-without-response-error) suggests to use `add_headers()` in the client. See [this example](https://stackoverflow.com/q/30336945).

@thomasyu888 Can you give it a try?

**Comment by thomasyu888** [comment]
@tschaffter This will take me some time to dig through the auto generated client code.  At first glance, [this function](https://github.com/nlpsandbox/nlpsandbox-client/blob/cf213d757764df34a8ea56f153c112e758e996ac/annotator/rest.py#L110) is probably where I have to add it, but I'm actually uncertain how the call is made.  I don't see an obvious `request.POST`

**Comment by tschaffter** [comment]
@thomasyu888 I can help with this ticket. What branch of the controller should I use for testing?

**Comment by thomasyu888** [comment]
@tschaffter, I keep trying to reproduce this error locally but I can't, I should try to run on the ec2 to see if I can reproduce. This error only happens when the person annotator is submitted to the queue. 

Create branch from `develop` on the client - after the possible fix is deployed:

1.  Log into the nlpsandbox-infrastructure ec2
2. Merge changes into develop and pull the newest docker image down on machine
3. Submit person annotator to TEST - person queue.

**Comment by thomasyu888** [comment]
Note: I think the code should be added around [here](https://github.com/nlpsandbox/nlpsandbox-client/blob/cf213d757764df34a8ea56f153c112e758e996ac/annotator/rest.py#L164-L169)?  

Also I'm slightly confused as to whether I `end_headers` should be added this to this repository OR if it should be added to the `nlpsandbox-client`

**Comment by thomasyu888** [comment]
https://stackoverflow.com/questions/48105448/python-http-server-client-remote-end-closed-connection-without-response-error

**Comment by thomasyu888** [comment]
I found a ticket that had a comment that says to add to the headers of the actual request.post (client change) :

https://stackoverflow.com/questions/33895739/python-requests-module-error-cant-load-any-url-remote-end-closed-connection

Also before all this, I'm going to do an update of the client because i want to use openapi-generator 5.0.0

**Comment by tschaffter** [comment]
@thomasyu888 Is it OK to give you back this ticket? I know your hands are as full as mine but I'd like to try to focus on writing the documentation (website and GitHub READMEs)

**Comment by tschaffter** [comment]
BTW I thought that the disconnection may happen when the request takes a lot of time. I added a sleep 60 seconds in the controller of the data annotator. The tried the documentation UI and there is a spin wheel displayed when the controller "works" and then the response was properly returned and shown in the documentation UI.

I'm now going to submit this image to the date annotation submission queue with a 30 second sleep and see if the workflow fails.

**Comment by tschaffter** [comment]
Waiting for 30 seconds, which is a long time in the world of API request, does not brake the workflow.

![image](https://user-images.githubusercontent.com/3056480/106684614-9a5b7580-657b-11eb-9450-de1867a44bd9.png)

**Comment by thomasyu888** [comment]
I'll take a closer look. This happens when I'm trying to store annotations into the data node though, not when I'm annotating

**Comment by tschaffter** [comment]
You can try to insert a `time.sleep(30)` in the post method of the controller. I just tried and the documentation UI waits patiently. But it would be interesting to add this wait and use the cli to see if the connection is closed due to a timeout. There are not many reason why a connection would close by itself (`Remote end closed connection without response`).

**Comment by thomasyu888** [comment]
Adding a `time.sleep(30)` would increase the annotation time by quite a bit - unfortunately, I don't think I can add `end_headers()` as well since the logic is part of 

```
https://github.com/nlpsandbox/data-node/blob/develop/server/openapi_server/__main__.py#L23
```

Trying this as well: https://github.com/nlpsandbox/nlpsandbox-client/pull/93/files
