### ISSUE TITLE
Adding annotations fails with ID and Contact Annotations 

### ISSUE THREAD

**Issue by gkowalski** [nlpsandbox/data-node#169]
#### Steps to reproduce the issue

1. Start up a 1.1.1 Data-node
2. Run my custom program to insert data from mcw into this node after inserting the data . I pretty much followed the same process as : [push_dataset.py](https://github.com/nlpsandbox/nlpsandbox-client/blob/develop/examples/push_dataset.py)
3. Received the error 
 
```
datanode.exceptions.ApiAttributeError: AnnotationCreateRequest has no attribute 'text_id_annotations' at ['annotation_create_request']['text_id_annotations']
```

The program worked up to this point. I am just trying to upload an empty set , but this worked for the other annotation types like date , person_name ,and physical_address.

#### Expected behavior

-Successful uploading of data 

#### Extra information

I tried to get data out of the node after successfully uploading data ( without the text_id_annotations and text_contact_annotations elements with : 

```
nlp-cli datanode list-annotations --data_node_host http://myhost.mcw.edu:8080/api/v1 --dataset_id mcwtest --annotation_store_id annotation2
```

and get the error : 

```
 nlp-cli datanode list-annotations --data_node_host http://myhost.mcw.edu:8080/api/v1 --dataset_id mcwtest --annotation_store_id annotation2
Traceback (most recent call last):
  File "/Users/gkowalsk/PycharmProjects/prodigy/venv/lib/python3.7/site-packages/datanode/model_utils.py", line 1599, in get_allof_instances
    allof_instance = allof_class(**kwargs)
  File "/Users/gkowalsk/PycharmProjects/prodigy/venv/lib/python3.7/site-packages/datanode/model_utils.py", line 1567, in wrapped_init
    return fn(self, *args, **kwargs)
  File "/Users/gkowalsk/PycharmProjects/prodigy/venv/lib/python3.7/site-packages/datanode/model/page_of_annotations_all_of.py", line 172, in __init__
    setattr(self, var_name, var_value)
  File "/Users/gkowalsk/PycharmProjects/prodigy/venv/lib/python3.7/site-packages/datanode/model_utils.py", line 168, in __setattr__
    self[attr] = value
  File "/Users/gkowalsk/PycharmProjects/prodigy/venv/lib/python3.7/site-packages/datanode/model_utils.py", line 353, in __setitem__
    self.set_attribute(name, value)
  File "/Users/gkowalsk/PycharmProjects/prodigy/venv/lib/python3.7/site-packages/datanode/model_utils.py", line 142, in set_attribute
    self._check_type, configuration=self._configuration)
  File "/Users/gkowalsk/PycharmProjects/prodigy/venv/lib/python3.7/site-packages/datanode/model_utils.py", line 1451, in validate_and_convert_types
    configuration=configuration
  File "/Users/gkowalsk/PycharmProjects/prodigy/venv/lib/python3.7/site-packages/datanode/model_utils.py", line 1403, in validate_and_convert_types
    check_type=_check_type
  File "/Users/gkowalsk/PycharmProjects/prodigy/venv/lib/python3.7/site-packages/datanode/model_utils.py", line 1284, in attempt_convert_item
    configuration, spec_property_naming)
  File "/Users/gkowalsk/PycharmProjects/prodigy/venv/lib/python3.7/site-packages/datanode/model_utils.py", line 1202, in deserialize_model
    return model_class(**kw_args)
  File "/Users/gkowalsk/PycharmProjects/prodigy/venv/lib/python3.7/site-packages/datanode/model_utils.py", line 1567, in wrapped_init
    return fn(self, *args, **kwargs)
  File "/Users/gkowalsk/PycharmProjects/prodigy/venv/lib/python3.7/site-packages/datanode/model/annotation.py", line 196, in __init__
    setattr(self, var_name, var_value)
  File "/Users/gkowalsk/PycharmProjects/prodigy/venv/lib/python3.7/site-packages/datanode/model_utils.py", line 168, in __setattr__
    self[attr] = value
  File "/Users/gkowalsk/PycharmProjects/prodigy/venv/lib/python3.7/site-packages/datanode/model_utils.py", line 353, in __setitem__
    self.set_attribute(name, value)
  File "/Users/gkowalsk/PycharmProjects/prodigy/venv/lib/python3.7/site-packages/datanode/model_utils.py", line 120, in set_attribute
    path_to_item
datanode.exceptions.ApiAttributeError: Annotation has no attribute 'textContactAnnotations' at ['received_data']['annotations'][0]['textContactAnnotations']

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/gkowalsk/PycharmProjects/prodigy/venv/bin/nlp-cli", line 33, in <module>
    sys.exit(load_entry_point('nlpsandbox-client==1.0.1', 'console_scripts', 'nlp-cli')())
  File "/Users/gkowalsk/PycharmProjects/prodigy/venv/lib/python3.7/site-packages/nlpsandboxclient/cli/__main__.py", line 19, in main
    cli()
  File "/Users/gkowalsk/PycharmProjects/prodigy/venv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/gkowalsk/PycharmProjects/prodigy/venv/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/gkowalsk/PycharmProjects/prodigy/venv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/gkowalsk/PycharmProjects/prodigy/venv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/gkowalsk/PycharmProjects/prodigy/venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/gkowalsk/PycharmProjects/prodigy/venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/gkowalsk/PycharmProjects/prodigy/venv/lib/python3.7/site-packages/nlpsandboxclient/cli/datanode_cli.py", line 106, in list_annotations
    utils.stdout_or_json(list(annotations), output)
  File "/Users/gkowalsk/PycharmProjects/prodigy/venv/lib/python3.7/site-packages/nlpsandboxclient/client.py", line 230, in list_annotations
    offset=offset, limit=limit
  File "/Users/gkowalsk/PycharmProjects/prodigy/venv/lib/python3.7/site-packages/datanode/api_client.py", line 772, in __call__
    return self.callable(self, *args, **kwargs)
  File "/Users/gkowalsk/PycharmProjects/prodigy/venv/lib/python3.7/site-packages/datanode/api/annotation_api.py", line 538, in __list_annotations
    return self.call_with_http_info(**kwargs)
  File "/Users/gkowalsk/PycharmProjects/prodigy/venv/lib/python3.7/site-packages/datanode/api_client.py", line 850, in call_with_http_info
    collection_formats=params['collection_format'])
  File "/Users/gkowalsk/PycharmProjects/prodigy/venv/lib/python3.7/site-packages/datanode/api_client.py", line 415, in call_api
    _check_type)
  File "/Users/gkowalsk/PycharmProjects/prodigy/venv/lib/python3.7/site-packages/datanode/api_client.py", line 227, in __call_api
    _check_type
  File "/Users/gkowalsk/PycharmProjects/prodigy/venv/lib/python3.7/site-packages/datanode/api_client.py", line 331, in deserialize
    configuration=self.configuration
  File "/Users/gkowalsk/PycharmProjects/prodigy/venv/lib/python3.7/site-packages/datanode/model_utils.py", line 1403, in validate_and_convert_types
    check_type=_check_type
  File "/Users/gkowalsk/PycharmProjects/prodigy/venv/lib/python3.7/site-packages/datanode/model_utils.py", line 1291, in attempt_convert_item
    raise conversion_exc
  File "/Users/gkowalsk/PycharmProjects/prodigy/venv/lib/python3.7/site-packages/datanode/model_utils.py", line 1284, in attempt_convert_item
    configuration, spec_property_naming)
  File "/Users/gkowalsk/PycharmProjects/prodigy/venv/lib/python3.7/site-packages/datanode/model_utils.py", line 1202, in deserialize_model
    return model_class(**kw_args)
  File "/Users/gkowalsk/PycharmProjects/prodigy/venv/lib/python3.7/site-packages/datanode/model_utils.py", line 1567, in wrapped_init
    return fn(self, *args, **kwargs)
  File "/Users/gkowalsk/PycharmProjects/prodigy/venv/lib/python3.7/site-packages/datanode/model/page_of_annotations.py", line 215, in __init__
    constant_args, model_args, self)
  File "/Users/gkowalsk/PycharmProjects/prodigy/venv/lib/python3.7/site-packages/datanode/model_utils.py", line 1847, in validate_get_composed_info
    allof_instances = get_allof_instances(self, model_args, constant_args)
  File "/Users/gkowalsk/PycharmProjects/prodigy/venv/lib/python3.7/site-packages/datanode/model_utils.py", line 1611, in get_allof_instances
    ) from ex
datanode.exceptions.ApiValueError: Invalid inputs given to generate an instance of 'PageOfAnnotationsAllOf'. The input data was invalid for the allOf schema 'PageOfAnnotationsAllOf' in the composed schema 'PageOfAnnotations'. Error=Annotation has no attribute 'textContactAnnotations' at ['received_data']['annotations'][0]['textContactAnnotations']

```

**Comment by thomasyu888** [comment]
@gkowalski this is because the client doesn't support it currently.

**Comment by tschaffter** [comment]
@gkowalski Meanwhile you should aim at fully supporting date, person nanme and physical address, i.e. have the entire dataset annotated and populated in the date node. I'll work this week on formatting the i2b2 data to the NLP Sandbox schemas (maybe tonight?) and then we will update the client tomorrow/Thursday. At least that's the plan.

**Comment by thomasyu888** [comment]
@gkowalski I think this issue is fixed, but to make sure, here are the steps:

1. Update the datanode (there should be version 1.1.2 now)
2. Install the `nlpsandbox-client` from source: https://github.com/nlpsandbox/nlpsandbox-client (There will be v2.0 coming out soon, but I just wanted to make sure everything was tested)
3. Push the example (should include `id`, `contact` and `covid_symptom` annotations.  See the [examples_bundles.json]( https://github.com/nlpsandbox/nlpsandbox-client/blob/develop/examples/example-patient-bundles.json)
      ```
      cd nlpsandbox-client
      python examples/push_dataset.py
      ```

**Comment by gkowalski** [comment]
(venv) [crdw@darvin:~/nlpsandbox-client]$ python examples/push_dataset.py
Traceback (most recent call last):
  File "examples/push_dataset.py", line 16, in <module>
    import nlpsandboxsdk
ModuleNotFoundError: No module named 'nlpsandboxsdk'
(venv) [crdw@darvin:~/nlpsandbox-client]$

hmm, not in the requirements.txt file.

**Comment by gkowalski** [comment]
pip install nlpsandbox-client --upgrade was also tried and didn't help

**Comment by tschaffter** [comment]
@gkowalski Tom is asking to install the python client from source (not from PyPi)

**Comment by gkowalski** [comment]
worked 

 python push_dataset.py
Deleting exist dataset: test-dataset
Creating dataset: test-dataset
Creating Fhir Store: evaluation
Creating Annotation Store: goldstandard
Creating patient: 110
Creating note (110-01) for patient (110)
Creating annotation for note: 110-01
Creating note (110-02) for patient (110)
Creating annotation for note: 110-02
Creating note (110-03) for patient (110)
Creating annotation for note: 110-03
Creating note (110-04) for patient (110)
Creating annotation for note: 110-04
Creating note (110-05) for patient (110)
Creating annotation for note: 110-05
