### ISSUE TITLE
Required fields break Flask app when the required property is inherited

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/data-node#78]
I had this error before validating the API spec with IBM OpenAPI Validator. Now I'm back to this issue which has not been solved by one of the many improvements I made using IBM OpenAPI Validator.

```
$ python -m openapi_server
Traceback (most recent call last):
  File "/home/tschaffter/.conda/envs/data-node-redesign/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/tschaffter/.conda/envs/data-node-redesign/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/c/Users/thoma/Documents/dev/nlp-sandbox-data-node-i2b2-2014/server/openapi_server/__main__.py", line 18, in <module>
    main()
  File "/mnt/c/Users/thoma/Documents/dev/nlp-sandbox-data-node-i2b2-2014/server/openapi_server/__main__.py", line 11, in main
    app.add_api('openapi.yaml',
  File "/home/tschaffter/.conda/envs/data-node-redesign/lib/python3.8/site-packages/connexion/apps/flask_app.py", line 57, in add_api
    api = super(FlaskApp, self).add_api(specification, **kwargs)
  File "/home/tschaffter/.conda/envs/data-node-redesign/lib/python3.8/site-packages/connexion/apps/abstract.py", line 144, in add_api
    api = self.api_cls(specification,
  File "/home/tschaffter/.conda/envs/data-node-redesign/lib/python3.8/site-packages/connexion/apis/abstract.py", line 75, in __init__
    self.specification = Specification.load(specification, arguments=arguments)
  File "/home/tschaffter/.conda/envs/data-node-redesign/lib/python3.8/site-packages/connexion/spec.py", line 153, in load
    return cls.from_file(spec, arguments=arguments)
  File "/home/tschaffter/.conda/envs/data-node-redesign/lib/python3.8/site-packages/connexion/spec.py", line 107, in from_file
    return cls.from_dict(spec)
  File "/home/tschaffter/.conda/envs/data-node-redesign/lib/python3.8/site-packages/connexion/spec.py", line 145, in from_dict
    return OpenAPISpecification(spec)
  File "/home/tschaffter/.conda/envs/data-node-redesign/lib/python3.8/site-packages/connexion/spec.py", line 38, in __init__
    self._validate_spec(raw_spec)
  File "/home/tschaffter/.conda/envs/data-node-redesign/lib/python3.8/site-packages/connexion/spec.py", line 239, in _validate_spec
    raise InvalidSpecification.create_from(e)
connexion.exceptions.InvalidSpecification: Required list has not defined properties: ['noteId']
```

**Comment by tschaffter** [comment]
The issue stems from this part of the built spec. In the example below, the model `StoredAnnotation_allOf` has a property `noteId`, however the validator failed to see it when requiring it.

```
    StoredAnnotation:
      allOf:
      - $ref: '#/components/schemas/Annotation'
      - $ref: '#/components/schemas/StoredAnnotation_allOf'
      description: A annotation in a text
      required:
      - noteId
      type: object
```

**Comment by tschaffter** [comment]
No longer relying on inheritance for `required` properties because it does not work.
